name: build and test of the branch
on:
  push:
    branches:
      - feature/*
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull and checkout from git repository
        run: |
          echo "pulling and checking out from git repository"
      - name: setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: build with maven
        run: |
          mvn clean install
          echo "build with maven"



